### ISSUE TITLE
Traceback on symbol lookup

### ISSUE THREAD

**Issue by ZenithDK** [thomasthorsen/SublimeToks#11]
I tried looking up a symbol that should be defined in the project, but looking at the console I have this:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 551, in run_
    return self.run(**args)
  File "C:\Users\lbig\AppData\Roaming\Sublime Text 3\Packages\Toks\SublimeToks.py", line 342, in run
    self.on_indexing_complete()
  File "C:\Users\lbig\AppData\Roaming\Sublime Text 3\Packages\Toks\SublimeToks.py", line 350, in on_indexing_complete
    self.pre_lookup_position = self.active_view_position()
  File "C:\Users\lbig\AppData\Roaming\Sublime Text 3\Packages\Toks\SublimeToks.py", line 207, in active_view_position
    return self.view.file_name() + ":" + str(row + 1) + ":" + str(col + 1)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by ZenithDK** [comment]
This happened for a function that only has a prototype, but didn't have a function body (as it is not in source, only in a precompiled lib).

I cannot reproduce the problem currently, unsure why.

**Comment by ZenithDK** [comment]
Okay, that's still a bug though, right? :)

**Comment by thomasthorsen** [comment]
Indeed it is
